language: c

dist: xenial

compiler:
  - gcc

env:
  - C_FLAGS="-std=c99"

before_install:
  - sudo apt-get -qq update

install:
  # Needed to compiler
  - sudo apt-get install flex bison

before_script:
  - cd src/main/compiler

script:
  - ./compila.sh ../programs/programa1.c
