service: compiler

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 128

functions:
  compile:
    handler: handler.compile
    events:
      - http:
          path: compile
          method: post
          cors: true
